name: Build Docker Image with Packer and Push to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_VERSION: v2.0.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3
      with:
        version: 'latest'

    - name: Initialize Packer
      run: packer init .

    - name: Validate Packer Configuration
      run: packer validate packer.pkr.hcl

    - name: Build Docker Image with Packer
      run: packer build packer.pkr.hcl

    - name: Log in to JFrog Artifactory Docker Registry
      run: |
        echo ${{ secrets.JFROG_PASSWORD }} | docker login ${{ secrets.JFROG_URL }} --username ${{ secrets.JFROG_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker tag ubuntu:20.04 ${{ secrets.JFROG_URL }}/s3cloudhub-example-d-docker/docker-example:latest
        docker push ${{ secrets.JFROG_URL }}/s3cloudhub-example-d-docker/docker-example:latest
        docker tag ubuntu:20.04 ${{ secrets.JFROG_URL }}/s3cloudhub-example-d-docker/docker-example:${{ env.DOCKER_IMAGE_VERSION }}
        docker push ${{ secrets.JFROG_URL }}/s3cloudhub-example-d-docker/docker-example:${{ env.DOCKER_IMAGE_VERSION }}

    - name: Logout from JFrog Artifactory
      run: |
        docker logout ${{ secrets.JFROG_URL }}
